---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-function"
      Handler: app.lambda_handler
      Runtime: python3.7
      CodeUri: code
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*" 
        - SNSPublishMessagePolicy:
            TopicName: "*"
