AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  SAM Template for exchange 

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  ExchangeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: code
      Handler: app.lambda_handler
      Runtime: python3.7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExchangeFunction:
    Description: "Exchange Lambda Function ARN"
    Value: !GetAtt ExchangeFunction.Arn
  ExchangeFunctionIamRole:
    Description: "Implicit IAM Role created for Exchange function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
